Enable to compile CUDA tests.

diff --git a/bin/hipfc b/bin/hipfc
--- a/bin/hipfc
+++ b/bin/hipfc
@@ -42,10 +42,18 @@ function usage(){
     -h          Print this help message
     -k          Keep temporary files
     -c          Compile to object code only
+    -lrocsolver Link to rocsolver library
     -lrocsparse Link to rocsparse library
     -lrocblas   Link to rocblas library
     -lrocfft    Link to rocfft library
+    -lrocrand   Link to rocrand library
     -lhipblas   Link to hipblas library
+    -lhiprand   Link to hiprand library
+    -lcusolver  Link to cusolver library
+    -lcusparse  Link to cusparse library
+    -lcublas    Link to cublas library
+    -lcufft     Link to cufft library
+    -lcurand    Link to curand library
 
    Options with values:       Defaults  
     -hipfort-compiler <bin>   $HIPFORT_COMPILER or gfortran
@@ -137,10 +145,33 @@ function getdname(){
    echo $__DIRN
 }
 
+function addrocmlib(){
+  name=$1
+  if [ ! -d $ROCM_DIR/$name/lib ] ; then 
+     echo "ERROR:  Directory $ROCM_DIR/$name/lib does not exist"
+     echo "        Please install $name"
+     exit $DEADRC
+  fi
+  LINKOPTS="$LINKOPTS -L$ROCM_DIR/$name/lib -l$name"
+}
+
+function addcudalib(){
+  name=$1
+  libdir=$CUDA_HOME/targets/x86_64-linux/lib
+  if [ ! -d $libdir ] ; then 
+     echo "ERROR:  Directory $libdir does not exist"
+     echo "        Please install CUDA"
+     exit $DEADRC
+  fi
+  LINKOPTS="$LINKOPTS -L$libdir -l$name"
+}
+
 #  --------  The main code starts here -----
 INCLUDES=""
 PASSTHRUARGS=""
 INPUTFILES=""
+ROCM_LIBS=""
+CUDA_LIBS=""
 #  Argument processing
 while [ $# -gt 0 ] ; do 
    case "$1" in 
@@ -160,10 +191,18 @@ while [ $# -gt 0 ] ; do
       -O0) 		FORTOPT=0 ;; 
       -o) 		OUTFILE=$2; shift ;; 
       -t)		TMPDIR=$2; shift ;; 
-      -lrocsparse)      ROCSPARSE=true ; PASSTHRUARGS+=" $1" ;;
-      -lrocblas)        ROCBLAS=true ; PASSTHRUARGS+=" $1" ;;
-      -lrocfft)         ROCFFT=true ; PASSTHRUARGS+=" $1" ;;
-      -lhipblas)        HIPBLAS=true ; PASSTHRUARGS+=" $1" ;;
+      -lrocsolver)      ROCM_LIBS+=" rocsolver" ;;
+      -lrocsparse)      ROCM_LIBS+=" rocsparse" ;;
+      -lrocblas)        ROCM_LIBS+=" rocblas" ;;
+      -lrocfft)         ROCM_LIBS+=" rocfft" ;;
+      -lhipsparse)      ROCM_LIBS+=" hipsparse" ;;
+      -lhipblas)        ROCM_LIBS+=" hipblas" ;;
+      -lhiprand)        ROCM_LIBS+=" hiprand" ;;
+      -lcusolver)       CUDA_LIBS+=" cusolver" ;;
+      -lcusparse)       CUDA_LIBS+=" cusparse" ;;
+      -lcufft)          CUDA_LIBS+=" cufft" ;;
+      -lcublas)         CUDA_LIBS+=" cublas" ;;
+      -lcurand)         CUDA_LIBS+=" curand" ;;
       --offload-arch)   HIPFORT_GPU=$2; shift ;;
       -triple)          TARGET_TRIPLE=$2; shift ;;
       -cuda-dir)        CUDA_HOME=$2; shift ;;
@@ -351,40 +390,14 @@ if [ $GEN_OBJECT_ONLY ]  ; then
    HIPCC_OPTS=" -c $HIPCC_OPTS"
    LINKOPTS=""
 else
-   LINKOPTS="$TARGET_LIBS -lstdc++ -L$HIPFORT/lib -lhipfort-$TARGET_ARCH"
-
-   if [ $ROCSPARSE ] ; then 
-     if [ ! -d $ROCM_DIR/rocsparse/lib ] ; then 
-        echo "ERROR:  Directory $ROCM_DIR/rocsparse/lib does not exist"
-        echo "        Please install rocsparse"
-        exit $DEADRC
-     fi
-     LINKOPTS="$LINKOPTS -L$ROCM_DIR/rocsparse/lib -lrocsparse"
-   fi
-   if [ $ROCBLAS ] ; then 
-     if [ ! -d $ROCM_DIR/rocblas/lib ] ; then 
-        echo "ERROR:  Directory $ROCM_DIR/rocblas/lib does not exist"
-        echo "        Please install rocblas"
-        exit $DEADRC
-     fi
-     LINKOPTS="$LINKOPTS -L$ROCM_DIR/rocblas/lib -lrocblas"
-   fi
-   if [ $HIPBLAS ] ; then 
-     if [ ! -d $ROCM_DIR/hipblas/lib ] ; then 
-        echo "ERROR:  Directory $ROCM_DIR/hipblas/lib does not exist"
-        echo "        Please install hipblas"
-        exit $DEADRC
-     fi
-     LINKOPTS="$LINKOPTS -L$ROCM_DIR/hipblas/lib -lhipblas"
-   fi
-   if [ $ROCFFT ] ; then 
-     if [ ! -d $ROCM_DIR/rocfft/lib ] ; then 
-        echo "ERROR:  Directory $ROCM_DIR/rocfft/lib does not exist"
-        echo "        Please install rocfft"
-        exit $DEADRC
-     fi
-     LINKOPTS="$LINKOPTS -L$ROCM_DIR/rocfft/lib -lrocfft"
-   fi
+   LINKOPTS="-L$HIPFORT/lib -lhipfort-$TARGET_ARCH"
+   for lib in $ROCM_LIBS; do
+     addrocmlib $lib
+   done
+   for lib in $CUDA_LIBS; do
+     addcudalib $lib
+   done
+   LINKOPTS="$LINKOPTS $TARGET_LIBS -lstdc++"
 fi
 
 # Separate hipcc inputs from fortran inputs
